# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  # This west.yml requires west 0.12s or later, because the "import"
  # feature used below was introduced then.
  version: 0.12

  # List of git repositories which make up the application
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: v2.1.0
      import: true

    - name: module-mbus
      url: https://github.com/addiva-elektronik/zephyr-mbus-module
      revision: main
      path: modules/lib/mbus

  self:
    path: mbus-app
